### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ghost** [fabriceb/gcalcron#17]
ERROR:root:Sync failed
Traceback (most recent call last):
  File "./gcalcron2.py", line 427, in main
    g.sync_gcal_to_cron()
  File "./gcalcron2.py", line 306, in sync_gcal_to_cron
    self.schedule_new_jobs(commandsList)
  File "./gcalcron2.py", line 262, in schedule_new_jobs
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Rpi python 2.7.3 on raspian

any idea on whats wrong ?

**Comment by ghost** [comment]
found the problem AT was not installed

**Comment by fabriceb** [comment]
Hi @zombu2, what was the name of the package containing "at" on Raspian?

**Comment by alfredomova** [comment]
@fabriceb solved it for me
> sudo apt-get install at
